version: "3.9"

services:
  nginx:
    build: 
      context: ./nginx
    networks:
      - wj_incept
    volumes:
      - wp-db:/var/www
    ports:  
      - 443:443
    depends_on:
      - wordpress
    restart: unless-stopped

  mariadb:
    build:
      context: ./mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    env_file: .env
    networks:
      - wj_incept
    volumes:
      - DB:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped
  
  wordpress:
    build:
      context: ./wordpress
    networks:
      - wj_incept
    volumes:
      - wp-db:/var/www/webapps/data    
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: unless-stopped

networks:
  wj_incept:
    driver: bridge

volumes:
  DB:
  wp-db:
