version: "3.9"
services:

  nginx:
    build: 
      context: ./nginx
        #network: wj_incept
    volumes:
      - wp-db:/var/www
    ports:  
      - 443:443
    restart: unless-stopped

  mariadb:
    build:
      context: ./mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    env_file: .env
      #network: wj_incept
    volumes:
      - DB:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped
  
  wordpress:
    build:
      context: ./wordpress
        #network: wj_incept
    volumes:
      - wp-db:/var/www/webapps/data    
    expose:
      - "9000"
    depends_on:
      - nginx
      - mariadb
    restart: unless-stopped

          #networks:
          #  wj_incept:

volumes:
  DB:
  wp-db:
